# Generated by Django 4.2.30 on 2026-04-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuardrailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_blocking', models.BooleanField(default=True)),
                ('prescription_blocking', models.BooleanField(default=True)),
                ('disclaimer_text', models.TextField(default='Disclaimer: This information is for educational purposes only and does not substitute professional medical advice. Always consult a doctor.')),
                ('emergency_keywords', models.TextField(default='suicide, heart attack, stroke, chest pain, bleeding heavily, unconscious, poison')),
                ('emergency_response', models.TextField(default='This sounds like a medical emergency. Please call 112 or visit the nearest hospital immediately.')),
                ('pii_redaction', models.BooleanField(default=True)),
                ('toxicity_filter', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Guardrail Configuration',
            },
        ),
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('local', 'Local / Custom')], default='gemini', max_length=20)),
                ('api_key', models.CharField(blank=True, default='', max_length=500)),
                ('model_name', models.CharField(default='gemini-1.5-flash', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=2048)),
                ('system_prompt', models.TextField(default='You are Arogya Sahayak, a helpful and knowledgeable medical AI assistant. You provide accurate, evidence-based health information based on the provided context. Always advise users to consult a real doctor for serious conditions. Do not hallucinate or make up medical facts. If the provided context does not contain relevant information, say so honestly.')),
            ],
            options={
                'verbose_name': 'LLM Configuration',
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='Arogya Sahayak', max_length=100)),
                ('support_email', models.EmailField(default='support@arogyasahayak.in', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('rate_limit_per_minute', models.IntegerField(default=20)),
                ('confidence_threshold', models.IntegerField(default=85)),
                ('fallback_message', models.TextField(default="I'm sorry, I don't have enough verified information to answer that safely. Please consult a registered medical practitioner.")),
            ],
            options={
                'verbose_name': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='VectorDBConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('chromadb', 'ChromaDB (Local)'), ('pinecone', 'Pinecone'), ('qdrant', 'Qdrant'), ('pgvector', 'pgvector')], default='chromadb', max_length=20)),
                ('api_key', models.CharField(blank=True, default='', max_length=500)),
                ('environment', models.CharField(blank=True, default='', max_length=100)),
                ('index_name', models.CharField(default='arogya-medical-index', max_length=100)),
                ('dimensions', models.IntegerField(default=384)),
                ('distance_metric', models.CharField(choices=[('cosine', 'Cosine Similarity'), ('l2', 'Euclidean Distance (L2)'), ('ip', 'Dot Product')], default='cosine', max_length=20)),
                ('top_k', models.IntegerField(default=5)),
                ('similarity_threshold', models.FloatField(default=0.75)),
            ],
            options={
                'verbose_name': 'Vector DB Configuration',
            },
        ),
    ]
