# Generated by Django 4.2.30 on 2026-04-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_url', models.URLField(blank=True, default='', max_length=500)),
                ('anon_key', models.CharField(blank=True, default='', max_length=500)),
                ('service_key', models.CharField(blank=True, default='', max_length=500)),
                ('database_url', models.CharField(blank=True, default='', max_length=1000)),
                ('jwt_secret', models.CharField(blank=True, default='', max_length=500)),
                ('is_configured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Supabase Configuration',
            },
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='model_name',
            field=models.CharField(default='gemini-2.5-flash', max_length=100),
        ),
        migrations.AlterField(
            model_name='vectordbconfig',
            name='provider',
            field=models.CharField(choices=[('chromadb', 'ChromaDB (Local)'), ('pgvector', 'pgvector (Supabase)'), ('pinecone', 'Pinecone'), ('qdrant', 'Qdrant')], default='chromadb', max_length=20),
        ),
    ]
