# Generated by Django 4.2.30 on 2026-04-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_supabaseconfig_alter_llmconfig_model_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('twilio', 'Twilio Sandbox'), ('meta', 'Meta Graph API')], default='twilio', max_length=20)),
                ('phone_number_id', models.CharField(blank=True, default='', max_length=100)),
                ('access_token', models.CharField(blank=True, default='', max_length=500)),
                ('verify_token', models.CharField(blank=True, default='arogya_secret_token', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
            },
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='google_maps_api_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
