# Generated by Django 4.2.30 on 2026-04-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('ai', 'AI'), ('system', 'System')], max_length=10),
        ),
    ]
