# Generated by Django 4.2.30 on 2026-04-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='supabase_uid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
