# Generated by Django 4.2.30 on 2026-04-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_supabase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
